# Generated by Django 5.1.1 on 2024-11-27 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 27, 16, 57, 34, 995082)
            ),
        ),
    ]
