# Generated by Django 4.2.16 on 2024-12-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_event_end_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 14, 13, 38, 300618)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("common_user", "Common User"), ("pma_admin", "PMA Admin")],
                default="common_user",
                max_length=50,
            ),
        ),
    ]
