# Generated by Django 4.2.16 on 2024-12-02 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_event_end_datetime_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 15, 5, 59, 68502)
            ),
        ),
    ]
